name: On Push

on:
  push:
    branches:
      - main
      - '[0-9]+.x'
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  typical-workflow:
    name: Workflow
    uses: bjerkio/workflows/.github/workflows/bun-typical.yml@v2

  todo-to-issue:
    name: Create issue from TODO comments
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Create issue from TODO comments 📝
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/)'
          label: |
            needs-refinement
            needs-triage
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-container:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      packages: write
      id-token: write

    concurrency:
      group: ${{ github.event.repository.full_name }}
      cancel-in-progress: false

    env:
      REGISTRY: ghcr.io

      # GitHub Container Registry Image Name
      GHCR_IMAGE: ghcr.io/${{ github.repository }}

      # Google Artifact Registry Image Name
      # prettier-ignore
      GAR_IMAGE: ${{ secrets.CONTAINER_REGISTRY }}/${{ github.event.repository.name }}

      IS_DEFAULT_BRANCH: ${{ github.ref == format('refs/heads/{0}',
        github.event.repository.default_branch) }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Log in to the Container registry 🔑
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Google 🔑
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Authenticate with Docker 🔑
        uses: docker/login-action@v3
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker meta 🏷
        id: meta-ghcr
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ env.IS_DEFAULT_BRANCH }}
            type=sha,prefix={{branch}}-,priority=1001

      - name: Docker meta 🏷
        id: meta-gar
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GAR_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ env.IS_DEFAULT_BRANCH }}
            type=sha,prefix={{branch}}-,priority=1001

      - name: Set up Docker Buildx 🔨
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Container 🛠
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ${{ steps.meta-ghcr.outputs.tags }}
            ${{ steps.meta-gar.outputs.tags }}
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: klyngeorg-eventorg
          region: europe-north1
          image: ${{ env.GAR_IMAGE }}:${{ steps.meta-ghcr.outputs.version }}
