name: On PR
on: [pull_request]

jobs:
  typical-workflow:
    name: Typical
    uses: bjerkio/workflows/.github/workflows/bun-typical.yml@v2

    concurrency:
      group: pr-${{ github.ref }}
      cancel-in-progress: true

